### ISSUE TITLE
Doesn't work on iPad UI/new iPhone UI

### ISSUE THREAD

**Issue by HexCodeFFF** [PoomSmart/Return-YouTube-Dislikes#11]
I've commented about this on one of the reddit posts and I believe the reason is cause the creator doesn't have an iPad to test it on. I have a jailbroken iPad and although I've never made a jailbreak tweak specifically I have high technical and programming knowledge and I'm willing to help, if you're up for that.

![image](https://user-images.githubusercontent.com/35177464/151699099-68e7a966-ba30-44ee-bc89-e1a4b816e05a.png)

The tweak is properly injected; the "enable vote submission" option shows in YouTube settings, the iPad app just has a different layout which the tweak isn't able to detect.

Edit: the iPhone app was updated to have a near identical dislike UI with the same issue

**Comment by PoomSmart** [comment]
That's another button style that we couldn't get one and test for ourselves because it mostly depends on the account you are using.

A helping hand is greatly appreciated. You can start by inspecting those buttons using FLEXAll tweak and seeing what kind of views they are. For example, version 1.6.1 targets the buttons that are rendered as `_ASDisplayView`.

**Comment by HexCodeFFF** [comment]
Seems to also be _ASDisplayView
![image](https://user-images.githubusercontent.com/35177464/151723647-2c6ef9e5-f9eb-4d64-b14b-ba138bfbce2c.png)
![image](https://user-images.githubusercontent.com/35177464/151723648-8896b78f-405c-4dab-a39c-fe3b72f4b0b1.png)
![image](https://user-images.githubusercontent.com/35177464/151723649-7c0138b6-2ff4-4a34-b7c1-d287f33271e1.png)

**Comment by HexCodeFFF** [comment]
![image](https://user-images.githubusercontent.com/35177464/151723885-7ba3549d-6299-4b8f-b9f9-c1fbee067f58.png)

**Comment by HexCodeFFF** [comment]
![image](https://user-images.githubusercontent.com/35177464/151724527-210179af-ea21-421d-bf3a-640ecd7aa9cd.png)

Obviously you'd know more than me but I don't see any obvious way to edit the text, there's no children objects or obvious properties

**Comment by kirb** [comment]
YouTube is using [Texture](https://github.com/texturegroup/texture) (aka AsyncDisplayKit). It’s a custom rendering engine with views that subclass `ASDisplayNode` as opposed to `UIView`. It renders nodes on a background thread and then displays them in a hierarchy of `_ASDisplayView`s. If you’re interested in helping us figure this out (it would be super appreciated!), I’d suggest taking a look through Texture’s [docs](https://texturegroup.org/docs/getting-started.html) to understand how it works. Particularly [the table here](https://texturegroup.org/docs/node-overview.html) should help make a bit of sense of what the equivalent node types are for common UIKit views.

**Comment by HexCodeFFF** [comment]
This is about the limit of my knowledge here, but i found out where the text data lives. trying to call some of its functions clears it, seems you need to create a new object or something beyond the capabilities of FLEXAll.

It seems if you copied the text object from the link button and put it in the same place as the dislike button it'd probably work. I haven't the slightest clue how but I'll test anything you want to try 

https://cdn.discordapp.com/attachments/827302684608430090/937518925246263306/RPReplay_Final1643591963.mp4

**Comment by PoomSmart** [comment]
@HexCodeFFF It has to be the case that `ELMContainerNode` doesn't have a matching accessibility label (https://github.com/PoomSmart/Return-YouTube-Dislikes/blob/main/Tweak.xm#L524) for the tweak to modify the dislike value correctly. Also, there isn't `ELMTextNode` to go through for the dislike button view. We have to create that from scratch.

**Comment by HexCodeFFF** [comment]
I was trying to modify the like count just to test but yeah you would need to create a new object for the dislike count. 

Im currently having issues installing the tweak on my iPhone due to "hash mismatches" which others have experienced, but the iPhone app seems to have the same UI as the iPad app now, at least for the dislike count, with the similar lack of dislike text object and existence of the accessibility label

![image](https://user-images.githubusercontent.com/35177464/151740708-0357732e-fc7c-4ba5-b86f-6f88037ca72c.png)

**Comment by HexCodeFFF** [comment]
Just installed the tweak by directly downloading the deb and then installing it manually and it doesn't work on my iPhone. The good news is that this means you should have a much easier time implementing this cause the iPhone and iPad use the same dislike UI
I'll update the issue title to reflect this

**Comment by HexCodeFFF** [comment]
Well it works now!
![image](https://user-images.githubusercontent.com/35177464/152277515-37908a83-1393-4164-b196-de16dc9017a0.png)
Closing!

**Comment by PoomSmart** [comment]
YouTube changed the style back? Hmm.

**Comment by HexCodeFFF** [comment]
Guess so. Works on my phone too. I like this style better anyways lol
