### ISSUE TITLE
App crashed when opening videos (very rare)

### ISSUE THREAD

**Issue by qnblackcat** [PoomSmart/Return-YouTube-Dislikes#12]
### Info
- YouTube v17.11.2
- RYD v1.6.3
- iOS 14.8/checkra1n/Substitute

### How to reproduce the bug
- Nothing special. The app just crashes when playing videos. However, it happens **very rarely**.  I've only encountered this crash a few times, but this is the first time Cr4shed recorded the crash log.

### Crashlog
- https://pastebin.com/EtxK47YR

**Comment by PoomSmart** [comment]
Version 1.6.4 is out to avoid this issue. See if the issue is gone.

**Comment by qnblackcat** [comment]
Up to this point everything is ok. I'll re-open the issue if something goes wrong.
