### ISSUE TITLE
freeze when playing playlist video,

### ISSUE THREAD

**Issue by sirik92** [PoomSmart/Return-YouTube-Dislikes#13]
when playing  more then 5 videos of playlist or 10 ytube app freezing  and not responding u have to kill the app and reopen it

**Comment by PoomSmart** [comment]
@sirik92 Are you sure this is because Return YouTube Dislike tweak?

**Comment by sirik92** [comment]
sorry for the delay and inconvenience i really tested it multiple time with only returnytdislike only enabled happen to me the freeze but now it's ok i guess i was wrong so sorry
