### ISSUE TITLE
Return YouTube Dislikes v1.6.5 .deb corrupt

### ISSUE THREAD

**Issue by SwiftWinds** [PoomSmart/Return-YouTube-Dislikes#14]
See:

![image](https://user-images.githubusercontent.com/12981958/172259436-d2cb4fb7-d92c-4144-bb1b-47c8225af101.png)

**Comment by PoomSmart** [comment]
Chariz team is looking into this issue. The tweak itself is fine.

**Comment by PoomSmart** [comment]
Fixed.

**Comment by SwiftWinds** [comment]
Thank you! 😄
