### ISSUE TITLE
New UI hides the count entirely

### ISSUE THREAD

**Issue by Proaxel** [PoomSmart/Return-YouTube-Dislikes#15]
At some point earlier today the UI buttons below the videos have been changed.

![CDC200CD-119C-4EFA-9609-A126B17F80DC](https://user-images.githubusercontent.com/9545347/174194389-8ad1905f-7549-4604-b5bf-6d4ef6c1f006.png)

This new UI completely hides the counter, like so. The tweak needs an update for this new change.

**Comment by alexandrius** [comment]
Can confirm

**Comment by arichorn** [comment]
I can confirm too

**Comment by PoomSmart** [comment]
#16
