### ISSUE TITLE
YT crashes after opening video

### ISSUE THREAD

**Issue by dayanch96** [PoomSmart/Return-YouTube-Dislikes#18]
Crash log: [YouTube-2022-09-24-203446.zip](https://github.com/PoomSmart/Return-YouTube-Dislikes/files/9638516/YouTube-2022-09-24-203446.zip)

**Comment by PoomSmart** [comment]
Are you using a debug build of RYD and also are you sticking to an old YouTube version?

**Comment by dayanch96** [comment]
latest github version but translated to Russian (K and M letters). YouTube 17.35.3

**Comment by PoomSmart** [comment]
@dayanch96 Your crash log says `17.33.2`.

**Comment by PoomSmart** [comment]
And this is obviously a debug build - did you modify anything in the source code?

```
Last Exception Backtrace:
0   CoreFoundation                	       0x1abe19d78 __exceptionPreprocess + 220
1   libobjc.A.dylib               	       0x1c4a7e734 objc_exception_throw + 60
2   CoreFoundation                	       0x1abef0fcc -[NSException init] + 0
3   Foundation                    	       0x1ad6c4020 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 236
4   Foundation                    	       0x1ad5953f4 -[NSObject(NSKeyValueCoding) valueForKey:] + 320
5   YouTubeDislikesReturn.dylib   	       0x10d8af748 _logos_method$_ungrouped$_ASDisplayView$didMoveToSuperview(_ASDisplayView*, objc_selector*) + 836
```

**Comment by dayanch96** [comment]
> @dayanch96 Your crash log says `17.33.2`.

Oh, my bad.

**Comment by dayanch96** [comment]
> And this is obviously a debug build - did you modify anything in the source code?
> 
> ```
> Last Exception Backtrace:
> 0   CoreFoundation                	       0x1abe19d78 __exceptionPreprocess + 220
> 1   libobjc.A.dylib               	       0x1c4a7e734 objc_exception_throw + 60
> 2   CoreFoundation                	       0x1abef0fcc -[NSException init] + 0
> 3   Foundation                    	       0x1ad6c4020 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 236
> 4   Foundation                    	       0x1ad5953f4 -[NSObject(NSKeyValueCoding) valueForKey:] + 320
> 5   YouTubeDislikesReturn.dylib   	       0x10d8af748 _logos_method$_ungrouped$_ASDisplayView$didMoveToSuperview(_ASDisplayView*, objc_selector*) + 836
> ```

Only K, M, B letters and removed pop-up window from %ctor

**Comment by PoomSmart** [comment]
It has to be around here that crashes. Can you debug it from the console maybe?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3608783/192290827-eb7b4f97-5c1e-45b0-b034-8c2e2402820d.png">

**Comment by dayanch96** [comment]
> It has to be around here that crashes. Can you debug it from the console maybe?
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/3608783/192290827-eb7b4f97-5c1e-45b0-b034-8c2e2402820d.png">

Actually, it’s my friends crashlog - I never had it before. Sadly, he said that just deleted RYD dylib from ipa I sent him after sharing crashlog.
I’ll just use original letters and test if it crashes.
