### ISSUE TITLE
Like/dislike count bug in new Youtube UI

### ISSUE THREAD

**Issue by Vreex** [PoomSmart/Return-YouTube-Dislikes#35]
Like/Dislike count not in the right places/offset

![ryd-yt-newui-bug](https://user-images.githubusercontent.com/83933964/198184379-a73c0675-8a68-4253-af9f-da868aa9de15.jpeg)

**Comment by arichorn** [comment]
That’s natural, PoomSmart did it that way so users can be able to see dislikes

**Comment by Vreex** [comment]
No, it's not natural.

At first glance, I thought it has dislikes and no likes until I looked closer. The desktop version is much more appropriate and orderly(for the lack of better word), aside from the margin issue.

That vs this(desktop):
![Screenshot from 2022-10-29 07-37-17](https://user-images.githubusercontent.com/83933964/198750722-d2023ac9-1c28-4426-8f82-f873da55896b.png)

**Comment by arichorn** [comment]
Mobile version is still different, it’s harder to implement on mobile because of the UIKit Limitions and YouTube App’s code

**Comment by Vreex** [comment]
That I can understand. For now, I will wait for a fix

**Comment by craftgeil** [comment]
Is it being worked on or is it just not possible?

**Comment by PoomSmart** [comment]
Fixed in 1.10.0
