### ISSUE TITLE
Exact Like Numbers [Backwards Compatibility - Feature Request]

### ISSUE THREAD

**Issue by arichorn** [PoomSmart/Return-YouTube-Dislikes#42]
Exact Like Numbers Toggle

what it does: same exact thing like the “Exact Dislike Numbers” but only for older YouTube versions that may not have Exact Like Numbers
![FC4F9C46-4420-4536-AEB2-8B49EB0A1C2A](https://user-images.githubusercontent.com/78001398/206081092-ccd49f43-7878-4b39-bb5f-b73d4d2799f1.jpeg)

**Comment by PoomSmart** [comment]
1.9.0

**Comment by arichorn** [comment]
Nice! gj with this one 👍
