### ISSUE TITLE
Red x

### ISSUE THREAD

**Issue by JackPlaysGames0510** [PoomSmart/Return-YouTube-Dislikes#55]
Can you fix this
![image](https://user-images.githubusercontent.com/48178959/232952481-e4ceaee4-35f7-4a9e-8131-90bbbcb6dd1a.png)

**Comment by PoomSmart** [comment]
Isn't this Return YouTube Dislike server issue?

**Comment by JackPlaysGames0510** [comment]
oh I see i didn't know i just wanted to know if you could do anyting about it

**Comment by PoomSmart** [comment]
Server may go down but will be up shortly after.
