### ISSUE TITLE
Dislike count disappears when scrolling

### ISSUE THREAD

**Issue by jaff80** [PoomSmart/Return-YouTube-Dislikes#56]
iOS version: 16.4.1 (20E252) Rapid Security Response: iOS 16.4.1 (a) (20E772520a)

uYouPlus version: v18.14.1-3.0

The bug: Sometimes, when you scroll down quickly and go back up fast, the dislike count disappears. It can appear back again if you go in full screen. (Probably more ways to bring it back) 

https://github.com/PoomSmart/Return-YouTube-Dislikes/assets/113552154/dd7ee503-310c-41b3-8181-a999ce752d15

It could be issue https://github.com/PoomSmart/Return-YouTube-Dislikes/issues/46

**Comment by PoomSmart** [comment]
Shouldn't happen anymore in recent versions.
