### ISSUE TITLE
Incompatible Pointer Types error when compiling

### ISSUE THREAD

**Issue by MaleNurse** [PoomSmart/Return-YouTube-Dislikes#62]
When compiling from source, I'm getting the following error:
```
Tweak.xm:677:38: error: incompatible pointer types initializing 'ELMContainerNode *__strong' with an expression of type 'ASDisplayNode *' [-Werror,-Wincompatible-pointer-types]
        ELMContainerNode *likeNode = snode.yogaChildren[0];

Tweak.xm:703:31: error: incompatible pointer types assigning to 'ELMTextNode *' from 'ASDisplayNode *' [-Werror,-Wincompatible-pointer-types]
            dislikeTextNode = node.yogaChildren[1];
```
Versions:
XCode 15.1
MacOS 14.3
iOS 17.2
Theos 2.5

Full `make troubleshoot` log: https://gist.github.com/MaleNurse/46beeaa5aa8a25a9966fc8f64c83664f

**Comment by MaleNurse** [comment]
Appears to be tied to the latest commit of YouTubeHeader ([980ea13](https://github.com/PoomSmart/YouTubeHeader/commit/980ea1362f82a82c2bd08c875d8602aa4da8c71f)). If I roll that back one commit, everything complies fine.

**Comment by PoomSmart** [comment]
Fixed.
