### ISSUE TITLE
Dislikes not working in Shorts

### ISSUE THREAD

**Issue by Mersid** [PoomSmart/Return-YouTube-Dislikes#64]
Return YouTube Dislikes does not show the number of dislikes for YouTube Shorts when viewed through the regular interface. Tested on YouTube versions 18.49.3, 19.02.1, and 19.04.3. with 1.11.6 of this tweak. It should be noted that if one were to somehow access a Shorts video such that it uses the regular video interface, such as via uYou's download tool and then "Play on YouTube", the dislikes shows up correctly. It's probably an issue with not properly hooking in to the Shorts UI's dislike button. Any chance you can investigate this? Thanks :)

**Comment by PoomSmart** [comment]
Sadly I'm unable to reproduce this issue on any of my devices, yet.

**Comment by Mersid** [comment]
Hello PoomSmart,

Thanks for investigating the issue! Oddly enough, the problem resolved itself a bit under a week ago. Odd, because it's been plaguing me across multiple devices for a month or two, but hey, it works now!

Cheers!

**Comment by PoomSmart** [comment]
Fixed in v1.11.8

**Comment by Mersid** [comment]
You're awesome, PoomSmart :)
