### ISSUE TITLE
YouTube crash if I play a video that the like count is hidden

### ISSUE THREAD

**Issue by dora727** [PoomSmart/Return-YouTube-Dislikes#67]
As I said in the title, I tried to play some videos with like count hidden, and all of them crashed
Some videos I tried:
https://youtube.com/watch?v=aH5GTif8ydE
https://youtube.com/watch?v=d0Zd5ij-NGU
and more video that like count was hidden.

crash log:
[ryd-crashlog.txt](https://github.com/user-attachments/files/15944137/ryd-crashlog.txt)

**Comment by PoomSmart** [comment]
Fixed
