### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by JackPlaysGames0510** [PoomSmart/Return-YouTube-Dislikes#68]
This crashes on version 19.25.4 and up

**Comment by PoomSmart** [comment]
Crash log?

**Comment by JackPlaysGames0510** [comment]
[YouTube-2024-07-03-035351.ips.zip](https://github.com/user-attachments/files/16085221/YouTube-2024-07-03-035351.ips.zip)

**Comment by PoomSmart** [comment]
Sideloaded, huh? Does it work if RYD is the only tweak there?

**Comment by JackPlaysGames0510** [comment]
Yes it does

**Comment by JackPlaysGames0510** [comment]
probably some confliction with you pip

**Comment by PoomSmart** [comment]
Should be fixed in v1.11.17
