### ISSUE TITLE
Settings pane doesn’t appear in the new YouTube Settings UI.

### ISSUE THREAD

**Issue by Weather-OS** [PoomSmart/Return-YouTube-Dislikes#71]
![4F86DBA5-E900-4134-8066-58AC5F5F7F82](https://github.com/PoomSmart/Return-YouTube-Dislikes/assets/84678467/a8538326-7d48-4d5f-b0b3-bd7fd7d0e866)

**Comment by PoomSmart** [comment]
Install YouGroupSettings tweak.

**Comment by Weather-OS** [comment]
Mark YouGroupSettings as a Dependency.

**Comment by eliliam** [comment]
@PoomSmart is YouGroupSettings still something that needs to be bundled in with this RYD tweak? I'm using [YTLite](https://github.com/dayanch96/YTLite) and trying to figure out how to enable vote submission, but YTLite doesn't list YouGroupSettings as one of the included Tweaks, leading me to think that I may be missing the RYD settings page entirely.

**Comment by PoomSmart** [comment]
@eliliam You need to inject YouGroupSettings into your YTLite sideloaded IPA.

**Comment by eliliam** [comment]
@PoomSmart do you know of any guides on how to do that?

**Comment by PoomSmart** [comment]
The easiest is you need to also inject DontEatMyContent tweak when you build YTLite IPA, so that YouGroupSettings gets injected too.

https://github.com/PoomSmart/YTLite/blob/main/.github/workflows/main.yml#L210C17-L210C35
