### ISSUE TITLE
Crashes when I scroll the buttons underneath the video

### ISSUE THREAD

**Issue by JackPlaysGames0510** [PoomSmart/Return-YouTube-Dislikes#73]
https://github.com/user-attachments/assets/649b26d4-13c2-4d46-9c9d-954785a2c373

**Comment by PoomSmart** [comment]
Crash log?

**Comment by JackPlaysGames0510** [comment]
[YouTube-2024-07-26-225218.ips.zip](https://github.com/user-attachments/files/16398289/YouTube-2024-07-26-225218.ips.zip)

**Comment by PoomSmart** [comment]
Fixed in v1.12.3

**Comment by JackPlaysGames0510** [comment]
thanks
