### ISSUE TITLE
Term Error (Error 1 and 2)

### ISSUE THREAD

**Issue by Jazooxd** [PoomSmart/Return-YouTube-Dislikes#74]
hi i try buil youre tweak but i got this error how i can fix it?

Log from terminal:

[Here](https://gofile.io/d/dLTBb9)

can you know how i can fix it? what i do wrong?

**Comment by PoomSmart** [comment]
This is not a tweak development support. Can you reach out to people in Theos Discord server instead?

https://theos.dev/discord
